include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "lib/generated/**"
    - "build/**"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_classes_with_only_static_members: false
    one_member_abstracts: false
    sort_pub_dependencies: false

custom_lint:
  rules:
    # riverpod_lint rules are enabled by default; tweak here if needed.
